---
site_name: Ops Catalog
site_url: https://ops-catalog.github.io/specification
repo_url: "https://github.com/ops-catalog/specification"
repo_name: "ops-catalog/specification"

nav:
    - 'Introduction': 'index.md'
    - 'Problem Statement': 'problems.md'
    - 'Why OCA?': 'whyoca.md'
    - 'Use Cases': 'usecases.md'
    - 'What is it???': 'whatisit.md'
    - 'Quickstart': 'quickstart.md'
    - 'Ecosystem': 'status.md'
    - 'Specification': 
      - 'Structure': spec/structure.md
      - 'Types':
        - 'Component': 'spec/types/component.md'
        - 'Store': 'spec/types/store.md'
        - 'Resource': 'spec/types/resource.md'
        - 'Endpoint': 'spec/types/endpoint.md'
        - 'Templates': 'spec/types/templates.md'
      - 'Catalog':
        - 'Running': 'catalog/running.md'  
        - 'Api Docs': 'catalog/api.md'
        - 'Configuration': 'catalog/configuration.md'
      - 'Discovery':
        - 'Specification': 'discovery/specification.md'
        - 'Workloads': 'discovery/workloads.md'
        - 'Resources': 'discovery/resource.md'
        - 'Endpoint': 'discovery/endpoint.md'
      - 'Fulfillment':
        - 'Specification': 'fulfillment/specification.md'
      - 'Scorecard': 'spec/scorecard.md'
    - Examples:
      - 'My Account': 'examples/my-account.md'
      - 'Deployer': 'examples/deploy.md'
    - Integrations:
      - 'Backstage': 'ui/backstage.md'
    - 'FAQs': 'faqs.md'
    - Issues:
        - 'Tracker': 'https://github.com/ops-catalog/specification/issues'
    - Download:
        - 'Pdf': '/pdf/document.pdf'
docs_dir: "docs"
site_dir: "site"

extra_css:
  - styles/css/global.css
use_directory_urls: true
dev_addr: '127.0.0.1:8000'


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details # For collapsible admonition-style blocks
  - pymdownx.betterem # For better emphasis handling
  # - pymdownx.critic # Optional: for diff-like markup, include if desired for future use
  - pymdownx.caret # For insert ^^ and delete ~~ syntax
  # - pymdownx.keys # Optional: for keyboard symbols, include if relevant use cases exist
  - pymdownx.mark # For highlighting text ==mark==
  # - pymdownx.tilde # Optional: for subscript/superscript, include if relevant
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true # Optional, for a different tab style
  - pymdownx.tasklist:
      custom_checkbox: true # For theme-styled checkboxes
  - pymdownx.magiclink # To auto-link URLs and emails
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      # slugify: !!python/name:pymdownx.slugs.uslugify # Consider if needed
  - admonition


theme:
  name: material
  highlightjs: true
  hljs_languages:
      - yaml
      - scala
  logo: assets/images/oca.svg
  favicon: assets/images/oca.svg
  features:
    - content.code.copy
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.integrate
    # New features to add
    - navigation.top # Adds a "Back to top" button
    - search.suggest # Enables search suggestions
    - search.highlight # Highlights search terms on target pages
    # - content.tabs.link # Add if pymdownx.tabbed is heavily used and cross-linking is desired
    - content.code.annotate # For adding annotations to code blocks
    - navigation.footer # Adds previous/next page links in the footer
    # - navigation.tabs # Optional: if a tabbed top-level navigation is desired instead of sidebar sections for main nav. Evaluate impact.
  font:
    text: Arial
    code: Jetbrains Mono

plugins:
  - render_swagger:
      allow_arbitrary_locations : true
      javascript: ../../assets/js/swagger-ui-bundle.js
      css: ../../assets/css/swagger-ui.css     
  - with-pdf

      
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-3PQ8DF9N34
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thank you for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- # (2)!
            Thank you for your feedback!
