---
site_name: Ops Catalog
site_url: https://github.com/open-catalog-alliance
repo_url: "https://github.com/open-catalog-alliance/specification"
repo_name: "open-catalog-alliance/specification"

nav:
    - 'Is it for me?': 'index.md'
    - 'Problem Statement': 'problems.md'
    - 'Why OCA?': 'whyoca.md'
    - 'Ecosystem': 'status.md'
    - 'Use Cases': 'usecases.md'
    - 'Specification': 
      - 'Structure': spec/structure.md
      - 'Types':
        - 'Component (wip)': 'spec/types/component.md'
        - 'Storage (wip)': 'spec/types/storage.md'
        - 'Resource (wip)': 'spec/types/resource.md'
        - 'Endpoint (wip)': 'spec/types/endpoint.md'
        - 'Templates': 'spec/types/templates.md'
      - 'Catalog':
        - 'Running (wip)': 'catalog/running.md'  
        - 'Configuration (wip)': 'catalog/configuration.md'
        - 'Api Docs': 'catalog/api.md'
      - 'Discovery':
        - 'Running (wip)': 'discovery/running.md'
        - 'Configuration (wip)': 'discovery/configuration.md'
        - 'Component (wip)': 'discovery/component.md'
        - 'Resource (wip)': 'discovery/resource.md'
        - 'Storage (wip)': 'discovery/storage.md'
        - 'Endpoint (wip)': 'discovery/endpoint.md'
      - 'Fulfillment':
        - 'Running (wip)': 'fulfillment/running.md'
        - 'Configuration (wip)': 'fulfillment/configuration.md'
        - 'Resource (wip)': 'fulfillment/resource.md'
      - 'Scorecard': 'spec/scorecard.md'
    - Examples:
      - 'My Account': 'examples/my-account.md'
      - 'Deployer': 'examples/deploy.md'
    - 'FAQs': 'faqs.md'
    - Issues:
        - 'Tracker': 'https://github.com/open-catalog-alliance/specification/issues'
    - 'Backlog': 'backlog.md'
    - 'Much later': 'TODO.md'
docs_dir: "docs"
site_dir: "site"

extra_css:
  - styles/css/global.css
use_directory_urls: true
dev_addr: '127.0.0.1:8000'


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html


theme:
  name: material
  highlightjs: true
  hljs_languages:
      - yaml
      - scala
  logo: assets/images/oca.svg
  favicon: assets/images/oca.svg
  features:
    - content.code.copy

plugins:
  - render_swagger:
      allow_arbitrary_locations : true
      javascript: ../../assets/js/swagger-ui-bundle.js
      css: ../../assets/css/swagger-ui.css      