---
site_name: Ops Catalog
site_url: https://github.com/open-catalog-alliance
repo_url: "https://github.com/open-catalog-alliance/specification"
repo_name: "open-catalog-alliance/specification"

nav:
    - index.md
    - Examples:
      - 'My Account': 'examples/my-account.md'
      - 'Deployer': 'examples/deploy.md'
    - Setup: []
    - Issues:
        - 'Tracker': 'https://github.com/open-catalog-alliance/specification/issues'
    - TODO.md
docs_dir: "docs"
site_dir: "site"

extra_css:
  - styles/css/global.css
use_directory_urls: true
dev_addr: '127.0.0.1:8000'


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


theme:
  name: material
  highlightjs: true
  hljs_languages:
      - yaml
      - scala
  logo: assets/images/oca.svg
  favicon: assets/images/oca.svg
  features:
    - content.code.copy
